title: 程泽群的博客
bio:  Talk is cheap.Show me the code.
baseurl: ""
url: "https://blog.codetiler.com"
repo: "chengzequn.github.io"                     #your_repo
client_id: "166f3c53beedb40499e0" #your_clientID
secret: "c329a22ed30fc370e70d644a63d609962ad8d17d"  #your_secrets
owner: "chengzequn"            #your_tonycheng1995
admin: ["chengzequn"]          #your_admin


email: chengzequn@foxmail.com
github: chengzequn
weibo: 5191968476      #your_weiboID

markdown: kramdown

#分页
paginate: 10
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-feed           #文章提要
  - jekyll-sitemap        #站点地图
  - jekyll-gist
  - jekyll-email-protect  #邮件混淆
  - jekyll-seo-tag        #seo
  - jekyll-paginate      #分页
